### PR TITLE
Better pod support

### PR DESCRIPTION
**Pull request by CNDW**
The goal of this pr is to add support for customizing the pod directory, and enable support for self contained component pods. I.E.

```
components
  |
  | --- select-box
  |          | --- component.js
  |          | --- template.hbs
  | --- fuzzy-widget
  |          | --- component.js
  |          | --- template.hbs
```

### CODE REVIEW

**Comment by knownasilya** [comment]
Wow, that's quite the PR for technically a deprecated library :smile_cat: 

I'll merge this and release a new version, since it seems like you are using this and not ember-cli for a specific reason.

**Comment by knownasilya** [comment]
v2.1.0 is released.

**Comment by knownasilya** [comment]
@CNDW do you want to be added as a collaborator?

**Comment by CNDW** [comment]
wow that was fast. I don't mind being added as a collaborator, I have a couple of project that are using ember but not the cli, so this lib is very useful!

**Comment by knownasilya** [comment]
What's your username on npm (so you can publish)?

**Comment by CNDW** [comment]
https://www.npmjs.com/~cndw

**Comment by knownasilya** [comment]
All set.

**Pull request merged**
