### PR TITLE
User Ember's internal module conventions and the latest resolver

### PR DESCRIPTION
**Pull request by CNDW**
This is fairly big, the api however remains unchanged save for some extra options. The streams have been consolidated and cleaned up a lot. I took out some of the no longer relevant tests and fixed the ones that remain, coverage is still really good, and I have been able to make this branch work with a fairly complex ember app internally with no changes other than swapping the new version. 

This fixes several issues with ember namespaces, opens the door to better addon support, and generally makes ember much more accessible for browserify based build systems.

### CODE REVIEW

**Comment by knownasilya** [comment]
Looks like some of the tests are still broken.

**Comment by CNDW** [comment]
Tests are fixed, it was a very minor change that broke them :/

**Comment by knownasilya** [comment]
I think we can merge and release 3.0..

**Comment by CNDW** [comment]
I think this qualifies as a milestone release

**Comment by knownasilya** [comment]
major? Using semver here, i.e. major.minor.patch

**Comment by CNDW** [comment]
Yea, I meant major :P the api has remained mostly the same, but anybody who is using a custom template will have to do some refactoring to reconcile the changes, I'd consider that breaking enough

**Comment by knownasilya** [comment]
Yeah, agreed. Also, do we need to tweak install instructions for the readme? Like do we need the additional modules, e.g. `hbsfy`..

**Comment by CNDW** [comment]
I've been thinking about that a lot. I wrote a custom browserify transform for htmlbars that I use, I wonder if we should just package one as it's pretty much a requirement for using this module to compile templates. The whole thing is made more complex by the fact that ember has not had a NPM friendly repo for a very long time. At some point I want to write out my entire build process for pulling ember into an existing project without ember-cli.

**Comment by knownasilya** [comment]
Actually ember being added to npm is in the works now, so it should probably be on npm within the next two releases.

**Comment by CNDW** [comment]
ah that's good to know, I've been pointing npm to the components/ember shim release tarball

**Pull request merged**
